name: Daily Wayback Machine Snapshot

on:
  schedule:
    - cron: '0 0 * * *'
  
  workflow_dispatch:

jobs:
  archive-website:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install waybackpy
        run: pip install waybackpy

      - name: Request snapshot from archive.org
        run: waybackpy --url "https://xdaforums.com/t/index-oneplus-12-roms-kernels-mods-tweaks-development-25-09-2025.4657133/" --save
            
      - name: Success message
        run: echo "Snapshot successfully requested!"
